name:                Spectrum
version:             0.1.0.0
github:              "StratusQuo/spectrum"
license:             MIT
author:              "Chris C"
maintainer:          "cchappellnyc@gmail.com"
copyright:           "2024 Chris C"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/spectrum-hs#readme>

dependencies:
- base >= 4.7 && < 5
- text
- ansi-terminal
- parsec
- containers
- colour  # Change 'color' to 'colour'
- regex-tdfa  # Add this for PCRE support
- mtl  # Add this for monadic transformers
- process

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  spectrum-hs-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Spectrum

tests:
  spectrum-hs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Spectrum
    - hspec
    - QuickCheck
